//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FnsBsoSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Operations
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public int UserId { get; set; }
        public string ActionType { get; set; }
        public string Details { get; set; }
    
        public virtual Sys_Users Sys_Users { get; set; }
    }
}
