//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FnsBsoSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Inventory
    {
        public int Id { get; set; }
        public int TypeId { get; set; }
        public string Series { get; set; }
        public int StartNumber { get; set; }
        public int EndNumber { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Main_Employees Main_Employees { get; set; }
        public virtual Ref_BlankStatuses Ref_BlankStatuses { get; set; }
        public virtual Ref_BlankTypes Ref_BlankTypes { get; set; }
    }
}
