//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FnsBsoSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Main_Employees()
        {
            this.Main_Inventory = new HashSet<Main_Inventory>();
            this.Sys_Users = new HashSet<Sys_Users>();
        }
    
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public int DeptId { get; set; }
        public int PosId { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FullName { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Ref_Departments Ref_Departments { get; set; }
        public virtual Ref_Positions Ref_Positions { get; set; }
        public virtual Ref_Ranks Ref_Ranks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Main_Inventory> Main_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Users> Sys_Users { get; set; }
    }
}
