//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FnsBsoSystem.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IFNS6_BsoSystemEntities : DbContext
    {
        public IFNS6_BsoSystemEntities()
            : base("name=IFNS6_BsoSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Log_Operations> Log_Operations { get; set; }
        public virtual DbSet<Main_Employees> Main_Employees { get; set; }
        public virtual DbSet<Main_Inventory> Main_Inventory { get; set; }
        public virtual DbSet<Ref_BlankStatuses> Ref_BlankStatuses { get; set; }
        public virtual DbSet<Ref_BlankTypes> Ref_BlankTypes { get; set; }
        public virtual DbSet<Ref_Departments> Ref_Departments { get; set; }
        public virtual DbSet<Ref_Positions> Ref_Positions { get; set; }
        public virtual DbSet<Ref_Ranks> Ref_Ranks { get; set; }
        public virtual DbSet<Sys_Users> Sys_Users { get; set; }
    }
}
